#!/bin/sh
#PBS -q cse
#PBS -l nodes=1:ppn=4
#PBS -N numt
#PBS -j oe
#PBS -l walltime=00:05:00

cd netID/mp0 #this is the path of the program that you're running
~/gennodelist.sh > nodelist

echo "Program Starting"
./charmrun ++nodelist nodelist ./arrayHello +p4
